### ISSUE TITLE
还想再请教下大佬，最后的车牌字符识别的输出如何不显示score呢?

### ISSUE THREAD

**Issue by Jasonx0123** [HuKai97/YOLOv5-LPRNet-Licence-Recognition#2]
请问我应该修改哪里的cv2.putText函数呢？

**Comment by HuKai97** [comment]
![image](https://user-images.githubusercontent.com/68494594/174971922-58a3041e-bdb1-40a0-9dd9-de0d6b9a6dfd.png)

检查下这个conf有没有值
