### ISSUE TITLE
解码问题

### ISSUE THREAD

**Issue by JFL888** [HuKai97/YOLOv5-LPRNet-Licence-Recognition#5]
运行test_yolov5.py报错：UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

**Comment by HuKai97** [comment]
![image](https://user-images.githubusercontent.com/68494594/224888547-b0bfcedc-3909-49f1-8b75-b1879389bc8b.png)
试一下
