### ISSUE TITLE
关于把ccpd转成yolo txt格式

### ISSUE THREAD

**Issue by littleloverlalala** [HuKai97/YOLOv5-LPRNet-Licence-Recognition#6]
请问ccpd2yolov5.py运行不出结果是怎么回事呢？txt文件是空的，我新建txt文件也写不进去，路径中也没有中文字呀。这是为什么呢？

如下；

if __name__ == '__main__':
    # det图片存储地址
    trainDir = r"D:/huohu/YOLOv5LPRNetLicenceRecognitionmaster/YOLOv5LPRNetLicenceRecognitionmaster/datasets/ccpd2yolo/images/train"
    validDir = r"D:/huohu/YOLOv5LPRNetLicenceRecognitionmaster/YOLOv5LPRNetLicenceRecognitionmaster/datasets/ccpd2yolo/images/val"
    testDir = r"D:/huohu/YOLOv5LPRNetLicenceRecognitionmaster/YOLOv5LPRNetLicenceRecognitionmaster/datasets/ccpd2yolo/images/test"
    # det txt存储地址
    train_txt_path = r"D:/huohu/YOLOv5LPRNetLicenceRecognitionmaster/YOLOv5LPRNetLicenceRecognitionmaster/datasets/ccpd2yolo/labels/train"
    val_txt_path = r"D:/huohu/YOLOv5LPRNetLicenceRecognitionmaster/YOLOv5LPRNetLicenceRecognitionmaster/datasets/ccpd2yolo/labels/val"
    test_txt_path = r"D:/huohu/YOLOv5LPRNetLicenceRecognitionmaster/YOLOv5LPRNetLicenceRecognitionmaster/datasets/ccpd2yolo/labels/test"
    txt_translate(trainDir, train_txt_path)
    txt_translate(validDir, val_txt_path)
    txt_translate(testDir, test_txt_path)图片能读到，但txt就是写不进去。

**Comment by HuKai97** [comment]
建议debug一下，这个数据集转换的代码应该不难的
